---

services:
  app:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset
    volumes:
      - artifacts:/opt/app/artifacts
      - selenium_downloads:/home/seluser/Downloads

volumes:
  artifacts:

