---

services:
  app:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !reset
    volumes:
      - artifacts:/opt/app/artifacts

  selenium:
    depends_on:
      - app
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900
    platform: linux/amd64
    networks:
      default:
        aliases:
          - selenium.test
    shm_size: 2g
    volumes:
      - ./tmp/selenium_downloads:/home/seluser/Downloads

volumes:
  artifacts:
