---

services:
  app:
    build: !reset
    environment:
      - CAPYBARA_SAVE_PATH=/opt/app/artifacts
    image: ${DOCKER_APP_IMAGE}
    depends_on:
      - selenium
    volumes: !override
      - artifacts:/opt/app/artifacts
      - selenium_downloads:/opt/app/tmp/selenium_downloads

volumes:
  artifacts:
