load_defaults: 7.33.1
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/geodata-test" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/geodata-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "https://geodata:utopian-treadle-fat-pug@geosolr-test.ucblib.org/solr/geodata" %>
