---

development:
  url: postgres://root:root@db/geodata-dev?pool=5

test:
  url: postgres://root:root@db/geodata-test?pool=5

production:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/geodata-prod' %>
